services:

  watcher:
    build:
      context: .
    volumes:
      - ./apulse_data:/app/static
      - ./config.js:/app/config.js
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - ./apulse_data:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    restart: unless-stopped
